//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfumer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public Nullable<int> Point_Of_Issue { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Receipt_Code { get; set; }
        public string Status { get; set; }
    
        public virtual Point_Of_Issue Point_Of_Issue1 { get; set; }
        public virtual User User { get; set; }
    }
}
